version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanagement
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery_worker:
    build: .
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app-network
    command: celery -A app.worker worker --loglevel=info

  celery_beat:
    build: .
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app-network
    command: celery -A app.worker beat --loglevel=info

networks:
  app-network:

volumes:
  postgres_data: